allowBuilds:
  esbuild: true
  msgpackr-extract: false
  workerd: false
  prisma: true
  "@prisma/engines": true
overrides:
  lodash: ">=4.17.24"
  deepmerge-ts: ">=8.0.0"
  mariadb: ">=3.4.6 <4"
  mysql2: ">=3.23.1 <4"
