sonar.projectKey=tupastilla-api
sonar.projectName=TuPastilla API
sonar.sources=src,prisma
sonar.tests=test
sonar.exclusions=src/generated/**
sonar.coverage.exclusions=src/server.ts,src/db.ts,src/repositories/prisma.ts,prisma/**
sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.sourceEncoding=UTF-8
